In [3]:
from math import log2

from torch import Tensor, sort

In [47]:
ys_true = torch.rand(5)
ys_pred = torch.rand(5)

In [221]:
ys_true

tensor([0.2048, 0.3451, 0.2961, 0.4787, 0.8041])

In [226]:
Tensor([0.2048, 0.3451, 0.3451, 0.2961, 0.4787, 0.8041])

tensor([0.2048, 0.3451, 0.3451, 0.2961, 0.4787, 0.8041])

In [102]:
sort(ys_pred, descending=True)

torch.return_types.sort(
values=tensor([0.8013, 0.5256, 0.3503, 0.0218, 0.0117]),
indices=tensor([2, 3, 1, 0, 4]))

In [112]:
def num_swapped_pairs(ys_true: Tensor, ys_pred: Tensor) -> int:
    
    ys_true_sort, sort_indices = sort(ys_true, descending=True)
    ys_pred_sort = ys_pred[sort_indices]

    print(ys_pred_sort)
    cnt = 0
    for i_ix, i in enumerate(ys_pred_sort):
        for y_ix, y in enumerate(ys_pred_sort):
            if (y_ix>i_ix) and (y>i):
                cnt+=1
                print(i, y)
                print(i_ix, y_ix)
    return cnt

In [114]:
# num_swapped_pairs(ys_true, ys_pred)

In [169]:
def compute_gain(y_value: float, gain_scheme: str) -> float:
    if gain_scheme=="const":
        return y_value
    elif gain_scheme=="exp2":
        return 2**y_value - 1
#         return pow(2,y_value) - 1
    else:
        return None

In [142]:
0.71324123412**3 - 1

-0.6371652279637434

In [191]:
pow(0.71324123412,3) - 1

-0.6371648706641574

In [185]:
def dcg(ys_true: Tensor, ys_pred: Tensor, gain_scheme: str) -> float:
    ys_pred_sort, sort_indices = sort(ys_pred, descending=True)
    ys_true_sort = ys_true[sort_indices] 
#     print(ys_true_sort)
    dcg_ = 0
    for ix, e in enumerate(ys_true_sort):
        dcg_ += compute_gain(e, gain_scheme)/log2(ix+2)
        
    return float(dcg_)

In [186]:
dcg(ys_true, ys_pred, gain_scheme='const')

1.1699225902557373

In [189]:
def ndcg(ys_true: Tensor, ys_pred: Tensor, gain_scheme: str = 'const') -> float:
    ys_ideal_true_sort, _ = sort(ys_true, descending=True)
    
    ideal_dcg = 0
    for ix, e in enumerate(ys_ideal_true_sort):
        ideal_dcg += compute_gain(e, gain_scheme)/log2(ix+2)
    
    ideal_dcg = float(ideal_dcg)
    
    dcg_ = dcg(ys_true, ys_pred, gain_scheme)
    
    return dcg_/ideal_dcg

In [192]:
ndcg(ys_true, ys_pred, gain_scheme='const')

0.7876030245686009

In [199]:
def precission_at_k(ys_true: Tensor, ys_pred: Tensor, k: int) -> float:
    
    ys_pred_sort, sort_indices = sort(ys_pred, descending=True)
    ys_true_sort = ys_true[sort_indices]
    ys_true_sort_topk = ys_true_sort[:k]
    
    ones_cnt = len([v for v in ys_true_sort_topk if v==1])
    if ones_cnt>0:
        return ones_cnt/len(ys_true_sort_topk)
    else:
        return -1

In [234]:
int((Tensor([0,0,0,1])==1).nonzero(as_tuple=False)[0])

3

In [11]:
for i in range(1,15):
    for j in range(1,15):
        if abs(i/j-0.46153846153846156)<0.00001:
            print(i,j)

6 13


In [334]:
def num_swapped_pairs(ys_true: Tensor, ys_pred: Tensor) -> int:
    
    ys_true_sort, sort_indices = sort(ys_true, descending=True)
    ys_pred_sort = ys_pred[sort_indices]
    ys_pred_sort = Tensor([0.8013, 0.1256, 0.1256, 0.3503, 0.0218, 0.0117, 0.3503])
    cnt = 0
    cnt_xy_list = []
    for x_ix, x in enumerate(ys_pred_sort):
        for y_ix, y in enumerate(ys_pred_sort):
            if bool(y_ix>x_ix) & bool(y>x) & ((x,y) not in cnt_xy_list):
                cnt_xy_list.append((x,y))
                print(x,y)
                cnt+=1
    return cnt

In [335]:
num_swapped_pairs(ys_true, ys_pred)

tensor(0.1256) tensor(0.3503)
tensor(0.0218) tensor(0.3503)
tensor(0.0117) tensor(0.3503)


3

In [308]:
l = [0,1,2,3,4]
l[:len(l)]

[0, 1, 2, 3, 4]

In [303]:
num_swapped_pairs(ys_true, ys_pred)

[(tensor(0.0117), tensor(0.5256)), (tensor(0.0117), tensor(0.3503)), (tensor(0.0117), tensor(0.8013)), (tensor(0.0117), tensor(0.0218)), (tensor(0.5256), tensor(0.8013)), (tensor(0.3503), tensor(0.5256)), (tensor(0.3503), tensor(0.8013))]


7

In [248]:
round(0.05555555555555555, 1)

0.1

In [280]:
Tensor([0,0,1,0,1,0,1])[:2]

tensor([0., 0.])

In [279]:
len([v for v in Tensor([0,0,1,0,1,0,1]) if v==1])

3

In [201]:
def reciprocal_rank(ys_true: Tensor, ys_pred: Tensor) -> float:
    ys_pred_sort, sort_indices = sort(ys_pred, descending=True)
    ys_true_sort = ys_true[sort_indices]
    one_idx = int((ys_true_sort==1).nonzero(as_tuple=False)[0])
    return 1/one_idx

In [203]:
def p_found(ys_true: Tensor, ys_pred: Tensor, p_break: float = 0.15 ) -> float:
    ys_pred_sort, sort_indices = sort(ys_pred, descending=True)
    ys_true_sort = ys_true[sort_indices]
    
    pfound_total = 0
    
    for ix, el in enumerate(ys_true_sort):
        if ix==0:
            p_look = 1
            p_f = p_look * ys_true_sort[ix]
        else: 
            p_look = p_look*(1-ys_true_sort[ix-1])*(1-p_break)
            p_f = p_look * ys_true_sort[ix]
        
        pfound_total += p_f
        
    return pfound_total

In [205]:
def average_precision(ys_true: Tensor, ys_pred: Tensor) -> float:
    
    ys_pred_sort, sort_indices = sort(ys_pred, descending=True)
    ys_true_sort = ys_true[sort_indices]
    
    ones_cnt = len([v for v in ys_true_sort if v==1])
    
    if ones_cnt>0:
        ap = 0
        for ix, el in enumerate(ys_true_sort):
            if el==1:
                ys_true_sort_filt = ys_true_sort[:ix]
                rec = len([v for v in ys_true_sort_filt if v==1])/len(ys_true_sort_filt)
                ap += rec
        return ap/ones_cnt
    else:
        return -1


In [218]:
[1,2,3][:3]

[1, 2, 3]